### ISSUE TITLE
Add modd configuration

### ISSUE THREAD

**Issue by licaonfee** [golang-templates/seed#7]
Example
modd.conf
```
**/*.go {
    prep:  go test -race -count 1 -timeout 30s -parallel 1 -coverprofile /tmp/cover.out  ./... && go tool cover -func=/tmp/cover.out 
}
```

this run tests and show coverage report by function every time you save a go file

**Comment by licaonfee** [comment]
this runs with modd (https://github.com/cortesi/modd)

**Comment by pellared** [comment]
@licaonfee 
Thanks for the proposal. I have checked https://github.com/cortesi/modd and looks pretty cool.
1. Can you please say how modd compares to https://github.com/oxequa/realize (from your experience)?
1. What editor do you use?
1. I think of adding following modd.conf. Do you think it would be OK?:
```
**/*.go {
    prep:  make all
}
```

**Comment by licaonfee** [comment]
1.- I didn't have experience with "realize" , i think modd is good enough 
2.- I use vscode without gopls , and golangci-lint with following flags "--fast --enable=dupl --enable=gocognit --enable=goconst --enable=gocritic --enable=gomnd --enable=gosec --enable=maligned --enable=misspell --enable=golint" 
3.- I like #8, i will use make with modd from now to avoid duplicate build/lint code

**Comment by pellared** [comment]
@licaonfee Thanks a lot for all. If you have any other ideas, requests then I will be to my best to help 😄 Closing.
